<link rel="stylesheet" type="text/css" media="screen" href="css/all.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/navbar.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/header.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/galery.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/commission.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/about.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/contact.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/footer.css">