<div class="col">


    <div class="card" style="width: 301px;">
        <div class="card-img-top">

            <a href="https://ko-fi.com/s/f9f163c2c2" alt="Armonia" target="_blank">
                <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                    <div class="wrapper">
                        <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1152585241832206356/Screenshot2023916148568.png?width=585&height=585"
                             src="https://media.discordapp.net/attachments/772173322896539668/1152585240234168361/Screenshot20239161441727417.png?width=585&height=585" class="cover-image" />
                    </div>
                    <img src="https://media.discordapp.net/attachments/772173322896539668/1152585241014325338/Screenshot20239161472340723.png?width=585&height=585" class="character" />
                </div>
            </a>

        </div>
        <div class="card-body">
            <h5 class="card-title">Armonia</h5>
            <p class="card-text">Je suis un texte</p>

            <p class="card-text" style="color: var(--colorall-main-purple)">30 €</p>
            <a href="https://ko-fi.com/s/f9f163c2c2" class="btn btn-primary">Acheter</a>
        </div>
    </div>

</div><div class="col">


    <div class="card" style="width: 301px;">
        <div class="card-img-top">

            <a href="https://ko-fi.com/s/f9f163c2c2" alt="Armonia" target="_blank">
                <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                    <div class="wrapper">
                        <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1152585241832206356/Screenshot2023916148568.png?width=585&height=585"
                             src="https://media.discordapp.net/attachments/772173322896539668/1152585240234168361/Screenshot20239161441727417.png?width=585&height=585" class="cover-image" />
                    </div>
                    <img src="https://media.discordapp.net/attachments/772173322896539668/1152585241014325338/Screenshot20239161472340723.png?width=585&height=585" class="character" />
                </div>
            </a>

        </div>
        <div class="card-body">
            <h5 class="card-title">Armonia</h5>
            <p class="card-text">Je suis un texte</p>

            <p class="card-text" style="color: var(--colorall-main-purple)">30 €</p>
            <a href="https://ko-fi.com/s/f9f163c2c2" class="btn btn-primary">Acheter</a>
        </div>
    </div>

</div><div class="col">


    <div class="card" style="width: 301px;">
        <div class="card-img-top">

            <a href="https://ko-fi.com/s/f9f163c2c2" alt="Armonia" target="_blank">
                <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                    <div class="wrapper">
                        <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1152585241832206356/Screenshot2023916148568.png?width=585&height=585"
                             src="https://media.discordapp.net/attachments/772173322896539668/1152585240234168361/Screenshot20239161441727417.png?width=585&height=585" class="cover-image" />
                    </div>
                    <img src="https://media.discordapp.net/attachments/772173322896539668/1152585241014325338/Screenshot20239161472340723.png?width=585&height=585" class="character" />
                </div>
            </a>

        </div>
        <div class="card-body">
            <h5 class="card-title">Armonia</h5>
            <p class="card-text">Je suis un texte</p>

            <p class="card-text" style="color: var(--colorall-main-purple)">30 €</p>
            <a href="https://ko-fi.com/s/f9f163c2c2" class="btn btn-primary">Acheter</a>
        </div>
    </div>

</div><div class="col">


    <div class="card" style="width: 301px;">
        <div class="card-img-top">

            <a href="https://ko-fi.com/s/f9f163c2c2" alt="Armonia" target="_blank">
                <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                    <div class="wrapper">
                        <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1152585241832206356/Screenshot2023916148568.png?width=585&height=585"
                             src="https://media.discordapp.net/attachments/772173322896539668/1152585240234168361/Screenshot20239161441727417.png?width=585&height=585" class="cover-image" />
                    </div>
                    <img src="https://media.discordapp.net/attachments/772173322896539668/1152585241014325338/Screenshot20239161472340723.png?width=585&height=585" class="character" />
                </div>
            </a>

        </div>
        <div class="card-body">
            <h5 class="card-title">Armonia</h5>
            <p class="card-text">Je suis un texte</p>

            <p class="card-text" style="color: var(--colorall-main-purple)">30 €</p>
            <a href="https://ko-fi.com/s/f9f163c2c2" class="btn btn-primary">Acheter</a>
        </div>
    </div>

</div>