<div id="about" class="container">


    <div class="row">

        <div class="col">


            <img src="https://media.discordapp.net/attachments/772173322896539668/1152635416378343454/vts-2023-08-25_19h25_41.png?width=585&height=585">


        </div>


        <div class="col">

            <h1>Retrouve-Moi sur <br>twitch !</h1>

            <p>Bonjour, je me présente, je m'appelle Aurore. Je suis une Vtubeuse passionnée par la création de contenus en tout genre. Je stream tous les jours sur Twitch, en particulier des jeux d'horreur mais bien d'autres choses encore ! Rejoignez-moi sur Twitch pour découvrir mes streams et passer un bon moment !</p>

            <a class="btn btn-light" href="https://www.twitch.tv/auroretvv"><i class="fab fa-twitch"></i> Twitch</a>

        </div>


    </div>


</div>