<div id="commission" class="container">

    <div class="container">
        <h2><i class="fas fa-paint-brush blueI"></i> Mes commission !</h2>
    </div>

    <div class="list-comi">



        <div id="service-second-but" class="row">



            <div class="col-6 image-container">
                <img style="margin-top: -38px;" class="image1"  src="https://media.discordapp.net/attachments/772173322896539668/1152640110593065031/Screenshot20239161886155861.png?width=585&height=585">
                <img style="width: 585px;margin-top: 33px;" class="image2" src="https://cdn.discordapp.com/attachments/772173322896539668/1152672637236027564/blob_2.svg">
            </div>


            <div class="col-5 container">

                <article>
                    <h3 class="art"><i class="fas fa-caret-right purpleI"></i> Création d'Avatar</h3>
                    <p class="art">Vous avez besoin d'un avatar 3D ? Je peux réaliser votre avatar !</p>
                    <div style="text-align: center">
                        <a class="btn btn-primary" href="#contact">Contactez-moi pour cette commission</a>
                    </div>
                </article>

                <article>
                    <h3 class="art"><i class="fas fa-caret-right purpleI"></i> BlendShapes</h3>
                    <p class="art">Vous voulez plus d'expressions et avoir un rendu naturel sur votre modèle Vroid ? Et bien je peux le faire pour vous, je lui rajouterai 32 BlendShapes.</p>
                    <div style="text-align: center">
                        <a class="btn btn-primary" href="#contact">Contactez-moi pour cette commission</a>
                    </div>
                </article>

            </div>

        </div>


        <div id="service-second-but" class="row">

            <div class="col-5 container">

                <article>
                    <h3 class="art"><i class="fas fa-caret-right purpleI"></i> Short</h3>
                    <p class="art">Je suis en capacité de créer le short que vous souhaitez !</p>
                    <div style="text-align: center">
                        <a class="btn btn-primary" href="#contact">Contactez-moi pour cette commission</a>
                    </div>
                </article>

                <article>
                    <h3 class="art"><i class="fas fa-caret-right purpleI"></i> Création de Poste</h3>
                    <p class="art">Si vous le souhaitez, je peux créer vos prochains posts sur les réseaux !</p>
                    <div style="text-align: center">
                        <a class="btn btn-primary" href="#contact">Contactez-moi pour cette commission</a>
                    </div>
                </article>

            </div>

            <div class="col-6 image-container">
                <img style="margin-top: -16px;" class="image1"  src="https://media.discordapp.net/attachments/772173322896539668/1152640113109643434/Screenshot20239161831455314.png?width=585&height=585">
                <img style="width: 585px;margin-top: -42px;" class="image2" src="https://cdn.discordapp.com/attachments/772173322896539668/1152676241535672450/blob_3.svg">
            </div>






        </div>









    </div>

</div>

<style>


    #commission{
        margin-top: 100px;
    }

    #service-second-but{

        margin-bottom: 50px;
    }

    #service-second-but h3.art{

        text-align: center;
        padding-top: 89px;
        padding-bottom: 30px;

    }

    .image-container {
        position: relative;
    }

    .image1, .image2 {
        position: absolute;
        top: 0;
        left: 0;
        transition: all .2s ease 0s;
    }

    .image-container:hover .image1, .image-container:hover .image2 {
        -webkit-transform: scale(1.10);
        -moz-transform: scale(1.10);
        -ms-transform: scale(1.10);
        -o-transform: scale(1.10);
        transform: scale(1.10);
    }

    .image2 {
        z-index: -1; /* Met l'image 2 en dessous de l'image 1 */
    }

    div#header .col-6:first-child{
        transition: all .2s ease 0s;
    }



</style>