<div id="contact">

    <div class="container">
        <h2><i class="fas fa-inbox blueI"></i> Contactez moi !</h2>
    </div>

<section id="contact-form" class="contact-wrap container">
    <form action="db/add.php" class="contact-form" method="GET">
        <div class="col-sm-12">
            <div class=" row">
                <div class="col-sm-6">
                    <div class="input-block">
                        <label for="">Prénom*</label>
                        <input type="text" class="form-control" name="firstName" required>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="input-block">
                        <label for="">Nom*</label>
                        <input type="text" class="form-control" name="lastName" required>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="input-block">
                <label for="">Email*</label>
                <input type="text" class="form-control" name="email" required>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="input-block">
                <label for="">Numéro de téléphone</label>
                <input type="text" class="form-control" name="phone">
            </div>
        </div>
        <div class="col-sm-12">
            <div class="input-block textarea">
                <label for="">Déposez votre message ici*</label>
                <textarea rows="3" type="text" class="form-control" name="content" required></textarea>
            </div>
        </div>
        <div class="col-sm-12">
            <input class="square-button" type="submit" value="Envoyé">
        </div>
    </form>
</section>

    <br>
    <p class="container" style="text-align: center; font-size: 10px; padding: 0px 40px"> * Toutes vos informations servent uniquement aux communications entre vous et l'Aurora. Elles ne serviront jamais à une autre utilisation. Elle ne seront donc jamais revendues, ou partagées.</p>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src="javascript/contact.js"></script>

</div>
