
<footer>
    <div class="footer">
        <div class="rowFoot">
            <a href="https://www.twitch.tv/auroretvv"><i class="fab fa-twitch"></i></a>
            <a href="https://www.youtube.com/@auroretvv"><i class="fab fa-youtube"></i></a>
            <a href="https://twitter.com/AuroreTV_v"><i class="fab fa-twitter"></i></a>
            <a href="https://www.instagram.com/auroretvv/"><i class="fab fa-instagram"></i></a>
        </div>

        <div class="rowFoot">
            <ul>
                <li><a href="#">Haut de page</a></li>
                <li><a href="#galery">Avatar</a></li>
                <li><a href="#commission">Commission</a></li>
                <li><a href="#about">A propos</a></li>
                <li><a href="#contact">Contact</a></li>
                <li><a href="#">Mentions Légales</a></li>
            </ul>
        </div>

        <div class="rowFoot">
            <p class="text-sm-center">
                AURORA Copyright © 2023 Aurora - All rights reserved <br> Create By: <a href="https://tyrolium.fr">Tyrolium</a>
            </p>
        </div>
    </div>
</footer>

