
    <div id="galery" class="container">


        <h2 style="margin-bottom: 70px">

            <i class="fas fa-heart blueI"></i> Adoptable !

        </h2>


        <div class="row galery">

            <div class="col">


                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href="https://ko-fi.com/s/f9f163c2c2" alt="Armonia" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="assets/avatar/armonia_back.png"
                                         src="assets/avatar/armonia_total.png" class="cover-image" />
                                </div>
                                <img src="assets/avatar/armonia_avatar.png" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Armonia</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">20 €</p>
                        <a target="_blank" href="https://ko-fi.com/s/f9f163c2c2" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>
            <div class="col">

                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href="https://ko-fi.com/s/adcac7b6f0" alt="BlackCat" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="assets/avatar/blackcat_back.png"
                                         src="assets/avatar/blackcat_total.png" class="cover-image" />
                                </div>
                                <img src="assets/avatar/blackcat_avatar.png" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">BlackCat</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">20 €</p>
                        <a target="_blank" href="https://ko-fi.com/s/adcac7b6f0" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>
            <div class="col">

                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href="https://ko-fi.com/s/02cc6417c5" alt="WhiteCat" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="assets/avatar/whitecat_back.png"
                                         src="assets/avatar/whitecat_total.png" class="cover-image" />
                                </div>
                                <img src="assets/avatar/whitecat_avatar.png" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">WhiteCat</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">20 €</p>
                        <a target="_blank" href="https://ko-fi.com/s/02cc6417c5" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>

            <div class="col">

                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href="https://ko-fi.com/s/41d7859d8e" alt="WhiteCat" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="assets/avatar/yumi_back.png"
                                         src="assets/avatar/yumi_total.png" class="cover-image" />
                                </div>
                                <img src="assets/avatar/yumi_avatar.png" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Yumi</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">20 €</p>
                        <a target="_blank" href="https://ko-fi.com/s/41d7859d8e" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>

            <div class="col">

                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href="https://www.etsy.com/fr/listing/1587563928/vtuber-3d-woodyna?click_key=d14a42e1b27b1c77f8ad39405c58376a5e7eb078%3A1587563928&click_sum=18fad8e1&ref=shop_home_active_1" alt="WhiteCat" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1169648549055713340/Screenshot20231121594131941.png?ex=65562b19&is=6543b619&hm=b71aa937370556f0d241ec481362f33c90d02add41d4d12237ad16f088626d2c&=&width=636&height=636"
                                         src="https://media.discordapp.net/attachments/772173322896539668/1169648547562520726/Site_1.png?ex=65562b18&is=6543b618&hm=58cdcbedaee117a2fe6d37593c1b8ac60054b9ad0cb6b958632451c85117b047&=&width=636&height=636" class="cover-image" />
                                </div>
                                <img src="https://media.discordapp.net/attachments/772173322896539668/1169648550393675887/Screenshot20231121528814288.png?ex=65562b19&is=6543b619&hm=64a34c344065dcbb85696d7f7607b419c8ae18e549e126a7056d4e6a3b56c07d&=&width=636&height=636" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Woodyna</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">12 €</p>
                        <a target="_blank" href="https://www.etsy.com/fr/listing/1587563928/vtuber-3d-woodyna?click_key=d14a42e1b27b1c77f8ad39405c58376a5e7eb078%3A1587563928&click_sum=18fad8e1&ref=shop_home_active_1" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>

            <div class="col">

                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href=" https://aurorastorefr.etsy.com/fr/listing/1603193119/vtuber-3d-mia-mia-basee-sur-mao-mao-des" alt="WhiteCat" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1170341534751785030/Screenshot20231141213718137.png?ex=6558b07d&is=65463b7d&hm=4ac3b0bdc003dab5562f72f348d2de595eb358c8ca09935d1d3e68d4667e95d9&=&width=702&height=702"
                                         src="https://media.discordapp.net/attachments/772173322896539668/1170341535477407805/Screenshot20231141233418334.png?ex=6558b07d&is=65463b7d&hm=d90c5b4f441c6a069d2a32df692709ae7dc42888b43ea55368b8d05dc9e13939&=&width=702&height=702" class="cover-image" />
                                </div>
                                <img src="https://media.discordapp.net/attachments/772173322896539668/1170341536010096730/Screenshot20231141291745917.png?ex=6558b07e&is=65463b7e&hm=72ee66e9098ea8387f01169d7b036725e8ecb279a5a29b4d1786dda6c94fae47&=&width=702&height=702" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Mia-Mia</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">6 €</p>
                        <a target="_blank" href="https://aurorastorefr.etsy.com/fr/listing/1603193119/vtuber-3d-mia-mia-basee-sur-mao-mao-des" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>

        </div>

        <script src="javascript/avatar.js"></script>

    </div>
