
    <div id="galery" class="container">


        <h2 style="margin-bottom: 70px">

            <i class="fas fa-heart blueI"></i> Adoptable !

        </h2>


        <div class="row galery">

            <div class="col">


                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href="https://ko-fi.com/s/f9f163c2c2" alt="Armonia" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1152585241832206356/Screenshot2023916148568.png?width=585&height=585"
                                         src="https://media.discordapp.net/attachments/772173322896539668/1152585240234168361/Screenshot20239161441727417.png?width=585&height=585" class="cover-image" />
                                </div>
                                <img src="https://media.discordapp.net/attachments/772173322896539668/1152585241014325338/Screenshot20239161472340723.png?width=585&height=585" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Armonia</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">20 €</p>
                        <a target="_blank" href="https://ko-fi.com/s/f9f163c2c2" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>
            <div class="col">

                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href="https://ko-fi.com/s/adcac7b6f0" alt="BlackCat" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1152592251256586360/Screenshot20239161580541805.png?width=585&height=585"
                                         src="https://media.discordapp.net/attachments/772173322896539668/1152592250514198568/Screenshot20239161553922539.png?width=585&height=585" class="cover-image" />
                                </div>
                                <img src="https://media.discordapp.net/attachments/772173322896539668/1152592251831201792/Screenshot20239161585931859.png?width=585&height=585" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">BlackCat</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">20 €</p>
                        <a target="_blank" href="https://ko-fi.com/s/adcac7b6f0" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>
            <div class="col">

                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href="https://ko-fi.com/s/adcac7b6f0" alt="WhiteCat" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1152593061134745671/Screenshot20239161538033380.png?width=585&height=585"
                                         src="https://media.discordapp.net/attachments/772173322896539668/1152593060379775077/Screenshot20239161512224122.png?width=585&height=585" class="cover-image" />
                                </div>
                                <img src="https://media.discordapp.net/attachments/772173322896539668/1152593059679309835/Screenshot20239161548443484.png?width=585&height=585" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">WhiteCat</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">20 €</p>
                        <a target="_blank" href="https://ko-fi.com/s/adcac7b6f0" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>

            <div class="col">

                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href="https://ko-fi.com/s/41d7859d8e" alt="WhiteCat" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1152646577899458711/Screenshot20239161818238182.png?width=585&height=585"
                                         src="https://media.discordapp.net/attachments/772173322896539668/1152646579673649254/ok.png?width=585&height=585" class="cover-image" />
                                </div>
                                <img src="https://media.discordapp.net/attachments/772173322896539668/1152646578742493214/Screenshot20239161836927369.png?width=585&height=585" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Yumi</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">20 €</p>
                        <a target="_blank" href="https://ko-fi.com/s/41d7859d8e" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>

            <div class="col">

                <div class="card" style="width: 301px;">
                    <div class="card-img-top">

                        <a href="https://www.etsy.com/fr/listing/1587563928/vtuber-3d-woodyna?click_key=d14a42e1b27b1c77f8ad39405c58376a5e7eb078%3A1587563928&click_sum=18fad8e1&ref=shop_home_active_1" alt="WhiteCat" target="_blank">
                            <div class="card-avatar"  onmouseover="changeImage(this)" onmouseout="restoreImage(this)">
                                <div class="wrapper">
                                    <img data-alt="https://media.discordapp.net/attachments/772173322896539668/1169648549055713340/Screenshot20231121594131941.png?ex=65562b19&is=6543b619&hm=b71aa937370556f0d241ec481362f33c90d02add41d4d12237ad16f088626d2c&=&width=636&height=636"
                                         src="https://media.discordapp.net/attachments/772173322896539668/1169648547562520726/Site_1.png?ex=65562b18&is=6543b618&hm=58cdcbedaee117a2fe6d37593c1b8ac60054b9ad0cb6b958632451c85117b047&=&width=636&height=636" class="cover-image" />
                                </div>
                                <img src="https://media.discordapp.net/attachments/772173322896539668/1169648550393675887/Screenshot20231121528814288.png?ex=65562b19&is=6543b619&hm=64a34c344065dcbb85696d7f7607b419c8ae18e549e126a7056d4e6a3b56c07d&=&width=636&height=636" class="character" />
                            </div>
                        </a>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Woodyna</h5>

                        <p class="card-text" style="color: var(--colorall-main-purple)">12 €</p>
                        <a target="_blank" href="https://www.etsy.com/fr/listing/1587563928/vtuber-3d-woodyna?click_key=d14a42e1b27b1c77f8ad39405c58376a5e7eb078%3A1587563928&click_sum=18fad8e1&ref=shop_home_active_1" class="btn btn-primary">Acheter</a>
                    </div>
                </div>

            </div>

        </div>

        <script src="javascript/avatar.js"></script>

    </div>
