<header>


    <div id="header">

    <?php require_once "./composant/navbar.phtml"; ?>

        <div class="row">
            <div class="col-6">
                <div>

                    <h1>Aurore Shop</h1>

                    <h3>azeaze</h3>


                </div>
            </div>
            <div class="col-6">



                <img src="https://media.discordapp.net/attachments/772173322896539668/1152560801899614298/Screenshot20239161315351153.png?width=512&height=512">



            </div>
        </div>
    </div>

    <style>

        div#header{


            height: 636px;

            /*background: rgb(222,0,255);*/
            /*background: -moz-radial-gradient(circle, rgba(222,0,255,1) 0%, rgba(65,0,75,1) 100%);*/
            /*background: -webkit-radial-gradient(circle, rgba(222,0,255,1) 0%, rgba(65,0,75,1) 100%);*/
            /*background: radial-gradient(circle, rgba(222,0,255,1) 0%, rgba(65,0,75,1) 100%);*/
            /*filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#de00ff",endColorstr="#41004b",GradientType=1);*/

            background: rgb(122,0,140);
            background: -moz-radial-gradient(circle, rgba(122,0,140,1) 0%, rgba(0,0,0,1) 100%);
            background: -webkit-radial-gradient(circle, rgba(122,0,140,1) 0%, rgba(0,0,0,1) 100%);
            background: radial-gradient(circle, rgba(122,0,140,1) 0%, rgba(0,0,0,1) 100%);
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#7a008c",endColorstr="#000000",GradientType=1);
        }

        div#header .row{
            --bs-gutter-x: unset!important;
        }

        div#header div.col-6:first-child{

            padding: 12% 0 12% 0;
            padding-left: 22%;

        }

        div#header div.col-6 h1,
        div#header div.col-6 h3{

            color: white;


        }


    </style>








</header>

