<header>


    <div id="header">

    <?php require_once "./composant/navbar.phtml"; ?>

        <div class="row">
            <div class="col-6">
                <div>

                    <h1>Aurora Store</h1>

                    <p>Bienvenue sur L'AuroraStore , un site spécialisé dans la vente d'avatars 3D, de montages au format short et de photo montages ! Si vous êtes à la recherche d'une façon unique et créative de vous exprimer en ligne, vous êtes au bon endroit.</p>


                </div>
            </div>
            <div class="col-6">



                <img src="https://media.discordapp.net/attachments/772173322896539668/1152560801899614298/Screenshot20239161315351153.png?width=512&height=512">



            </div>
        </div>
    </div>

</header>

