<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="Aurora Store">
<meta name="description" content="Bienvenue sur L'AuroraStore , un site spécialisé dans la vente d'avatars 3D, de montages au format short et de photo montages ! Si vous êtes à la recherche d'une façon unique et créative de vous exprimer en ligne, vous êtes au bon endroit."/>
<meta property="og:title" content="Aurora Store"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://aurorastore.fr/"/>
<meta property="og:image" content="https://aurorastore.fr/assets/icone.png"/>
<meta property="og:description" content="Bienvenue sur L'AuroraStore , un site spécialisé dans la vente d'avatars 3D, de montages au format short et de photo montages ! Si vous êtes à la recherche d'une façon unique et créative de vous exprimer en ligne, vous êtes au bon endroit."/>