<header id="nav-desktop">
        <div class="clear"></div>
        <nav id="navbar-scroll">
            <div class="site-title"><h1><a href="#">AuroraStore</a></h1></div>
            <ul class="center-ul">

                <li><a href="#galery"><i class="fas fa-heart"></i> Avatar</a></li>

                <li><a href="#commission"><i class="fas fa-paint-brush"></i> Commission</a></li>

                <li><a href="#about"><i class="fas fa-address-card"></i> A propos</a></li>

                <li><a href="#contact"><i class="fas fa-inbox"></i> Contact</a></li>

            </ul>
        </nav>
        <script src="javascript/navbar.js"></script>
</header>

<header id="nav-mobile">
    <h1><a href="#">AuroraStore</a></h1>

    <input id="burger" type="checkbox" />

    <label for="burger">
        <span></span>
        <span></span>
        <span></span>
    </label>

    <nav>
        <ul>

            <li ><a href="#galery">Avatar</a></li>

            <li ><a href="#commission">Commission</a></li>

            <li class="nav-active"><a href="#about">A propos</a></li>

            <li ><a href="#contact">Contact</a></li>

        </ul>
    </nav>
</header>
