<header id="nav-desktop">
    <div class="clear"></div>
    <nav id="navbar-scroll" class="fixed-header">
        <div class="site-title visible-title"><h1><a href="#">AuroraStore</a></h1></div>
        <ul class="">

            <li><a href="index#galery"><i class="fas fa-heart"></i> Avatar</a></li>

            <li><a href="index#commission"><i class="fas fa-paint-brush"></i> Commission</a></li>

            <li><a href="index#about"><i class="fas fa-address-card"></i> A propos</a></li>

            <li><a href="index#contact"><i class="fas fa-inbox"></i> Contact</a></li>

        </ul>
    </nav>
</header>

<header id="nav-mobile">
    <h1><a href="#">AuroraStore</a></h1>

    <input id="burger" type="checkbox" />

    <label for="burger">
        <span></span>
        <span></span>
        <span></span>
    </label>

    <nav>
        <ul>

            <li><a href="index#galery">Avatar</a></li>

            <li><a href="index#commission">Commission</a></li>

            <li><a href="index#about">A propos</a></li>

            <li><a href="index#contact">Contact</a></li>

        </ul>
    </nav>
</header>
