<header id="nav-desktop">
    <!--<div class="header-banner" style="background-image: url('<?php /*echo $env_navImg; */?>');">
        <h1><img src="<?php /*echo $env_logoTransp; */?>"></h1>
    </div>-->

        <div class="clear"></div>
        <nav>
            <div class="site-title"><h1><a href="#">AuroraStore</a></h1></div>
            <ul class="center-ul">

                <li ><a href="#galery">Avatar</a></li>

                <li ><a href="#commission">Commission</a></li>

                <li class="nav-active"><a href="#about">A propos</a></li>

                <li ><a href="#contact">Contact</a></li>

            </ul>
        </nav>
        <script src="javascript/navbar.js"></script>
</header>

<header id="nav-mobile">
    <h1><a href="#">AuroraStore</a></h1>

    <input id="burger" type="checkbox" />

    <label for="burger">
        <span></span>
        <span></span>
        <span></span>
    </label>

    <nav>
        <ul>

            <li ><a href="#galery">Avatar</a></li>

            <li ><a href="#commission">Commission</a></li>

            <li class="nav-active"><a href="#about">A propos</a></li>

            <li ><a href="#contact">Contact</a></li>

        </ul>
    </nav>
</header>